//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sofco.Resources.Workflow {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Workflow {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Workflow() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sofco.Resources.Workflow.Workflow", typeof(Workflow).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a workflow/workflow.cannotDoTransition.
        /// </summary>
        public static string CannotDoTransition {
            get {
                return ResourceManager.GetString("CannotDoTransition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a workflow/workflow.entityNull.
        /// </summary>
        public static string EntityNull {
            get {
                return ResourceManager.GetString("EntityNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a workflow/workflow.nextStateNull.
        /// </summary>
        public static string NextStateNull {
            get {
                return ResourceManager.GetString("NextStateNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a workflow/workflow.parametersNull.
        /// </summary>
        public static string ParametersNull {
            get {
                return ResourceManager.GetString("ParametersNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a workflow/workflow.transitionSuccess.
        /// </summary>
        public static string TransitionSuccess {
            get {
                return ResourceManager.GetString("TransitionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a workflow/workflow.userHasNoAccess.
        /// </summary>
        public static string UserHasNoAccess {
            get {
                return ResourceManager.GetString("UserHasNoAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a workflow/workflow.workflowNull.
        /// </summary>
        public static string WorkflowNull {
            get {
                return ResourceManager.GetString("WorkflowNull", resourceCulture);
            }
        }
    }
}
