//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sofco.Resources.Recruitment {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class JobSearch {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal JobSearch() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sofco.Resources.Recruitment.JobSearch", typeof(JobSearch).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a recruitment/jobSearch.addSuccess.
        /// </summary>
        public static string AddSuccess {
            get {
                return ResourceManager.GetString("AddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a recruitment/jobSearch.cannotChangeStatus.
        /// </summary>
        public static string CannotChangeStatus {
            get {
                return ResourceManager.GetString("CannotChangeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a recruitment/jobSearch.clientMustBeNull.
        /// </summary>
        public static string ClientMustBeNull {
            get {
                return ResourceManager.GetString("ClientMustBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a recruitment/jobSearch.clientRequired.
        /// </summary>
        public static string ClientRequired {
            get {
                return ResourceManager.GetString("ClientRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a recruitment/jobSearch.commentsRequired.
        /// </summary>
        public static string CommentsRequired {
            get {
                return ResourceManager.GetString("CommentsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a recruitment/jobSearch.contactAdded.
        /// </summary>
        public static string ContactAdded {
            get {
                return ResourceManager.GetString("ContactAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a recruitment/jobSearch.createdDateGreaterThanSuspendedDate.
        /// </summary>
        public static string CreatedDateGreaterThanSuspendedDate {
            get {
                return ResourceManager.GetString("CreatedDateGreaterThanSuspendedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a recruitment/jobSearch.dateRequired.
        /// </summary>
        public static string DateRequired {
            get {
                return ResourceManager.GetString("DateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a recruitment/jobSearch.documentNumberRequired.
        /// </summary>
        public static string DocumentNumberRequired {
            get {
                return ResourceManager.GetString("DocumentNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a recruitment/jobSearch.languageRequired.
        /// </summary>
        public static string LanguageRequired {
            get {
                return ResourceManager.GetString("LanguageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a recruitment/jobSearch.marketStudyRequired.
        /// </summary>
        public static string MarketStudyRequired {
            get {
                return ResourceManager.GetString("MarketStudyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a recruitment/jobSearch.maximunSalaryIsRequired.
        /// </summary>
        public static string MaximunSalaryIsRequired {
            get {
                return ResourceManager.GetString("MaximunSalaryIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a recruitment/jobSearch.modelNull.
        /// </summary>
        public static string ModelNull {
            get {
                return ResourceManager.GetString("ModelNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a recruitment/jobSearch.notFound.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a recruitment/jobSearch.quantityRequired.
        /// </summary>
        public static string QuantityRequired {
            get {
                return ResourceManager.GetString("QuantityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a recruitment/jobSearch.reasonCauseRequired.
        /// </summary>
        public static string ReasonCauseRequired {
            get {
                return ResourceManager.GetString("ReasonCauseRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a recruitment/jobSearch.selectorRequired.
        /// </summary>
        public static string SelectorRequired {
            get {
                return ResourceManager.GetString("SelectorRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a recruitment/jobSearch.statusRequired.
        /// </summary>
        public static string StatusRequired {
            get {
                return ResourceManager.GetString("StatusRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a recruitment/jobSearch.studyRequired.
        /// </summary>
        public static string StudyRequired {
            get {
                return ResourceManager.GetString("StudyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a recruitment/jobSearch.suspendedDateGreaterThanReopenDate.
        /// </summary>
        public static string SuspendedDateGreaterThanReopenDate {
            get {
                return ResourceManager.GetString("SuspendedDateGreaterThanReopenDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a recruitment/jobSearch.timeHiringRequired.
        /// </summary>
        public static string TimeHiringRequired {
            get {
                return ResourceManager.GetString("TimeHiringRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a recruitment/jobSearch.updateSuccess.
        /// </summary>
        public static string UpdateSuccess {
            get {
                return ResourceManager.GetString("UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a recruitment/jobSearch.userRequired.
        /// </summary>
        public static string UserRequired {
            get {
                return ResourceManager.GetString("UserRequired", resourceCulture);
            }
        }
    }
}
