//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sofco.Resources.Rrhh {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class License {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal License() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sofco.Resources.Rrhh.License", typeof(License).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to rrhh/license.approveSuccess.
        /// </summary>
        public static string ApproveSuccess {
            get {
                return ResourceManager.GetString("ApproveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to rrhh/license.authPendingSuccess.
        /// </summary>
        public static string AuthPendingSuccess {
            get {
                return ResourceManager.GetString("AuthPendingSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to rrhh/license.cannotChangeStatus.
        /// </summary>
        public static string CannotChangeStatus {
            get {
                return ResourceManager.GetString("CannotChangeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to rrhh/license.commentsRequired.
        /// </summary>
        public static string CommentsRequired {
            get {
                return ResourceManager.GetString("CommentsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to rrhh/license.datesRequired.
        /// </summary>
        public static string DatesRequired {
            get {
                return ResourceManager.GetString("DatesRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to rrhh/license.daysWrong.
        /// </summary>
        public static string DaysWrong {
            get {
                return ResourceManager.GetString("DaysWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to rrhh/license.employeeNotFound.
        /// </summary>
        public static string EmployeeNotFound {
            get {
                return ResourceManager.GetString("EmployeeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to rrhh/license.employeeRequired.
        /// </summary>
        public static string EmployeeRequired {
            get {
                return ResourceManager.GetString("EmployeeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to rrhh/license.endDateLessThanStartDate.
        /// </summary>
        public static string EndDateLessThanStartDate {
            get {
                return ResourceManager.GetString("EndDateLessThanStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to rrhh/license.examDaysTakenExceeded.
        /// </summary>
        public static string ExamDaysTakenExceeded {
            get {
                return ResourceManager.GetString("ExamDaysTakenExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to rrhh/license.examDescriptionRequired.
        /// </summary>
        public static string ExamDescriptionRequired {
            get {
                return ResourceManager.GetString("ExamDescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to rrhh/license.examTypeRequired.
        /// </summary>
        public static string ExamTypeRequired {
            get {
                return ResourceManager.GetString("ExamTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to rrhh/license.fileAdded.
        /// </summary>
        public static string FileAdded {
            get {
                return ResourceManager.GetString("FileAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to rrhh/license.licenseTypeNotFound.
        /// </summary>
        public static string LicenseTypeNotFound {
            get {
                return ResourceManager.GetString("LicenseTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to rrhh/license.licenseTypeUpdate.
        /// </summary>
        public static string LicenseTypeUpdate {
            get {
                return ResourceManager.GetString("LicenseTypeUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to rrhh/license.managerNotFound.
        /// </summary>
        public static string ManagerNotFound {
            get {
                return ResourceManager.GetString("ManagerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to rrhh/license.managerRequired.
        /// </summary>
        public static string ManagerRequired {
            get {
                return ResourceManager.GetString("ManagerRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to rrhh/license.notFound.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to rrhh/license.pendingSuccess.
        /// </summary>
        public static string PendingSuccess {
            get {
                return ResourceManager.GetString("PendingSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to rrhh/license.rejectSuccess.
        /// </summary>
        public static string RejectSuccess {
            get {
                return ResourceManager.GetString("RejectSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to rrhh/license.saveSuccess.
        /// </summary>
        public static string SaveSuccess {
            get {
                return ResourceManager.GetString("SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to rrhh/license.sectorRequired.
        /// </summary>
        public static string SectorRequired {
            get {
                return ResourceManager.GetString("SectorRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to rrhh/license.typeRequired.
        /// </summary>
        public static string TypeRequired {
            get {
                return ResourceManager.GetString("TypeRequired", resourceCulture);
            }
        }
    }
}
