//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sofco.Resources.Rrhh {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Prepaid {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Prepaid() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sofco.Resources.Rrhh.Prepaid", typeof(Prepaid).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a rrhh/prepaid.cannotClose.
        /// </summary>
        public static string CannotClose {
            get {
                return ResourceManager.GetString("CannotClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a rrhh/prepaid.closeSuccess.
        /// </summary>
        public static string CloseSuccess {
            get {
                return ResourceManager.GetString("CloseSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a rrhh/prepaid.dateClosed.
        /// </summary>
        public static string DateClosed {
            get {
                return ResourceManager.GetString("DateClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La cantidad de beneficiarios es distinta..
        /// </summary>
        public static string DifferenceInBeneficiaires {
            get {
                return ResourceManager.GetString("DifferenceInBeneficiaires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El costo del plan es distinto..
        /// </summary>
        public static string DifferenceInCosts {
            get {
                return ResourceManager.GetString("DifferenceInCosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El periodo es diferente al año y mes seleccionados.
        /// </summary>
        public static string DifferenceInPeriod {
            get {
                return ResourceManager.GetString("DifferenceInPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El plan es distinto..
        /// </summary>
        public static string DifferenceInPlan {
            get {
                return ResourceManager.GetString("DifferenceInPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El empleado no fue informado en ningun archivo de prepaga.
        /// </summary>
        public static string EmployeeMissing {
            get {
                return ResourceManager.GetString("EmployeeMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El empleado no existe en Tiger..
        /// </summary>
        public static string EmployeeNotFound {
            get {
                return ResourceManager.GetString("EmployeeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a rrhh/prepaid.fileEmpty.
        /// </summary>
        public static string FileEmpty {
            get {
                return ResourceManager.GetString("FileEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a rrhh/prepaid.fileWrong.
        /// </summary>
        public static string FileWrong {
            get {
                return ResourceManager.GetString("FileWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a rrhh/prepaid.monthError.
        /// </summary>
        public static string MonthError {
            get {
                return ResourceManager.GetString("MonthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a rrhh/prepaid.noDataUpdate.
        /// </summary>
        public static string NoDataUpdate {
            get {
                return ResourceManager.GetString("NoDataUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a rrhh/prepaid.noItemsSelected.
        /// </summary>
        public static string NoItemsSelected {
            get {
                return ResourceManager.GetString("NoItemsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a rrhh/prepaid.notFound.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a rrhh/prepaid.notImplemented.
        /// </summary>
        public static string NotImplemented {
            get {
                return ResourceManager.GetString("NotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a rrhh/prepaid.statusEmpty.
        /// </summary>
        public static string StatusEmpty {
            get {
                return ResourceManager.GetString("StatusEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a rrhh/prepaid.updateSuccess.
        /// </summary>
        public static string UpdateSuccess {
            get {
                return ResourceManager.GetString("UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a rrhh/prepaid.yearError.
        /// </summary>
        public static string YearError {
            get {
                return ResourceManager.GetString("YearError", resourceCulture);
            }
        }
    }
}
