//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sofco.Resources.Admin {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Role {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Role() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sofco.Resources.Admin.Role", typeof(Role).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to admin/role.created.
        /// </summary>
        public static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to admin/role.deleted.
        /// </summary>
        public static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to admin/role.descriptionExist.
        /// </summary>
        public static string DescriptionExist {
            get {
                return ResourceManager.GetString("DescriptionExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to admin/role.descriptionMaxLengthError.
        /// </summary>
        public static string DescriptionMaxLengthError {
            get {
                return ResourceManager.GetString("DescriptionMaxLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to admin/role.descriptionRequired.
        /// </summary>
        public static string DescriptionRequired {
            get {
                return ResourceManager.GetString("DescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to admin/role.disabled.
        /// </summary>
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to admin/role.enabled.
        /// </summary>
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to admin/role.modulesUpdated.
        /// </summary>
        public static string ModulesUpdated {
            get {
                return ResourceManager.GetString("ModulesUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to admin/role.notFound.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to admin/role.roleFunctionalitiesUpdated.
        /// </summary>
        public static string RoleFunctionalitiesUpdated {
            get {
                return ResourceManager.GetString("RoleFunctionalitiesUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to admin/role.roleMenusUpdated.
        /// </summary>
        public static string RoleMenusUpdated {
            get {
                return ResourceManager.GetString("RoleMenusUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to admin/role.roleModuleAlreadyCreated.
        /// </summary>
        public static string RoleModuleAlreadyCreated {
            get {
                return ResourceManager.GetString("RoleModuleAlreadyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to admin/role.roleModuleAlreadyRemoved.
        /// </summary>
        public static string RoleModuleAlreadyRemoved {
            get {
                return ResourceManager.GetString("RoleModuleAlreadyRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to admin/role.updated.
        /// </summary>
        public static string Updated {
            get {
                return ResourceManager.GetString("Updated", resourceCulture);
            }
        }
    }
}
