//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sofco.Resources.es.Billing {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Solfac {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Solfac() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sofco.Resources.es.Billing.Solfac", typeof(Solfac).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to billing/solfac.billUpdated.
        /// </summary>
        public static string BillUpdated {
            get {
                return ResourceManager.GetString("BillUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to billing/solfac.cancelledSucces.
        /// </summary>
        public static string CancelledSucces {
            get {
                return ResourceManager.GetString("CancelledSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to billing/solfac.cannotChangeStatus.
        /// </summary>
        public static string CannotChangeStatus {
            get {
                return ResourceManager.GetString("CannotChangeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to billing/solfac.cashedDateGreaterThanInvoiceDate.
        /// </summary>
        public static string CashedDateGreaterThanInvoiceDate {
            get {
                return ResourceManager.GetString("CashedDateGreaterThanInvoiceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to billing/solfac.cashedDateGreaterThanToday.
        /// </summary>
        public static string CashedDateGreaterThanToday {
            get {
                return ResourceManager.GetString("CashedDateGreaterThanToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to billing/solfac.cashedDateLessThanSolfacInvoiceDate.
        /// </summary>
        public static string CashedDateLessThanSolfacInvoiceDate {
            get {
                return ResourceManager.GetString("CashedDateLessThanSolfacInvoiceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to billing/solfac.cashedDateLessThanSolfacStartDate.
        /// </summary>
        public static string CashedDateLessThanSolfacStartDate {
            get {
                return ResourceManager.GetString("CashedDateLessThanSolfacStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to billing/solfac.cashedDateRequired.
        /// </summary>
        public static string CashedDateRequired {
            get {
                return ResourceManager.GetString("CashedDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to billing/solfac.cashUpdated.
        /// </summary>
        public static string CashUpdated {
            get {
                return ResourceManager.GetString("CashUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to billing/solfac.commentRequired.
        /// </summary>
        public static string CommentRequired {
            get {
                return ResourceManager.GetString("CommentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to billing/solfac.creditNoteTotalExceeded.
        /// </summary>
        public static string CreditNoteTotalExceededError {
            get {
                return ResourceManager.GetString("CreditNoteTotalExceededError", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to billing/solfac.deleted.
        /// </summary>
        public static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to billing/solfac.detailDeleted.
        /// </summary>
        public static string DetailDeleted {
            get {
                return ResourceManager.GetString("DetailDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to billing/solfac.detailNotFound.
        /// </summary>
        public static string DetailNotFound {
            get {
                return ResourceManager.GetString("DetailNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to billing/solfac.errorSaveOnHitos.
        /// </summary>
        public static string ErrorSaveOnHitos {
            get {
                return ResourceManager.GetString("ErrorSaveOnHitos", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to billing/solfac.fileAdded.
        /// </summary>
        public static string FileAdded {
            get {
                return ResourceManager.GetString("FileAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to billing/solfac.fileDeleted.
        /// </summary>
        public static string FileDeleted {
            get {
                return ResourceManager.GetString("FileDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to billing/solfac.hitoQuantityRequired.
        /// </summary>
        public static string HitoQuantityRequired {
            get {
                return ResourceManager.GetString("HitoQuantityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to billing/solfac.hitoUnitPriceRequired.
        /// </summary>
        public static string HitoUnitPriceRequired {
            get {
                return ResourceManager.GetString("HitoUnitPriceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to billing/solfac.infoUpdate.
        /// </summary>
        public static string InfoUpdate {
            get {
                return ResourceManager.GetString("InfoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to billing/solfac.invoiceCodeAlreadyExist.
        /// </summary>
        public static string InvoiceCodeAlreadyExist {
            get {
                return ResourceManager.GetString("InvoiceCodeAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to billing/solfac.invoiceCodeRequired.
        /// </summary>
        public static string InvoiceCodeRequired {
            get {
                return ResourceManager.GetString("InvoiceCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to billing/solfac.invoiceDateGreaterThanCashedDate.
        /// </summary>
        public static string InvoiceDateGreaterThanCashedDate {
            get {
                return ResourceManager.GetString("InvoiceDateGreaterThanCashedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to billing/solfac.invoiceDateGreaterThanToday.
        /// </summary>
        public static string InvoiceDateGreaterThanToday {
            get {
                return ResourceManager.GetString("InvoiceDateGreaterThanToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to billing/solfac.invoiceDateLessThanSolfacStartDate.
        /// </summary>
        public static string InvoiceDateLessThanSolfacStartDate {
            get {
                return ResourceManager.GetString("InvoiceDateLessThanSolfacStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to billing/solfac.invoiceDateRequired.
        /// </summary>
        public static string InvoiceDateRequired {
            get {
                return ResourceManager.GetString("InvoiceDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to billing/solfac.invoiceDeleted.
        /// </summary>
        public static string InvoiceDeleted {
            get {
                return ResourceManager.GetString("InvoiceDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to billing/solfac.invoicedSuccess.
        /// </summary>
        public static string InvoicedSuccess {
            get {
                return ResourceManager.GetString("InvoicedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to billing/solfac.invoicePendingSuccess.
        /// </summary>
        public static string InvoicePendingSuccess {
            get {
                return ResourceManager.GetString("InvoicePendingSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to billing/solfac.invoicesAdded.
        /// </summary>
        public static string InvoicesAdded {
            get {
                return ResourceManager.GetString("InvoicesAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to billing/solfac.managementControlRejectedSuccess.
        /// </summary>
        public static string ManagementControlRejectedSuccess {
            get {
                return ResourceManager.GetString("ManagementControlRejectedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to billing/solfac.notFound.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to billing/solfac.notFounds.
        /// </summary>
        public static string NotFounds {
            get {
                return ResourceManager.GetString("NotFounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to billing/solfac.pendingByManagementControlSuccess.
        /// </summary>
        public static string PendingByManagementControlSuccess {
            get {
                return ResourceManager.GetString("PendingByManagementControlSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to billing/solfac.percentageLessThan0.
        /// </summary>
        public static string PercentageLessThan0 {
            get {
                return ResourceManager.GetString("PercentageLessThan0", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to billing/solfac.provinceRequired.
        /// </summary>
        public static string ProvinceRequired {
            get {
                return ResourceManager.GetString("ProvinceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to billing/solfac.solfacCreated.
        /// </summary>
        public static string SolfacCreated {
            get {
                return ResourceManager.GetString("SolfacCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to billing/solfac.solfacUpdated.
        /// </summary>
        public static string SolfacUpdated {
            get {
                return ResourceManager.GetString("SolfacUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to billing/solfac.timeLimitLessThan0.
        /// </summary>
        public static string TimeLimitLessThan0 {
            get {
                return ResourceManager.GetString("TimeLimitLessThan0", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to billing/solfac.totalPercentageError.
        /// </summary>
        public static string TotalPercentageError {
            get {
                return ResourceManager.GetString("TotalPercentageError", resourceCulture);
            }
        }
    }
}
