//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sofco.Resources.Mails {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MailSubjectResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MailSubjectResource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sofco.Resources.Mails.MailSubjectResource", typeof(MailSubjectResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apertura analítica {0}.
        /// </summary>
        public static string AddAnalytic {
            get {
                return ResourceManager.GetString("AddAnalytic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cierre analítica {0}.
        /// </summary>
        public static string CloseAnalytic {
            get {
                return ResourceManager.GetString("CloseAnalytic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cierre para Costos analítica: {0}.
        /// </summary>
        public static string CloseForExpensesAnalytic {
            get {
                return ResourceManager.GetString("CloseForExpensesAnalytic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Baja de recurso.
        /// </summary>
        public static string EmployeeEndConfirmation {
            get {
                return ResourceManager.GetString("EmployeeEndConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Notificación de baja.
        /// </summary>
        public static string EmployeeEndNotification {
            get {
                return ResourceManager.GetString("EmployeeEndNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Novedades Recursos.
        /// </summary>
        public static string EmployeeNews {
            get {
                return ResourceManager.GetString("EmployeeNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a HITOS sin Solfac.
        /// </summary>
        public static string HitosWithoutSolfac {
            get {
                return ResourceManager.GetString("HitosWithoutSolfac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Anulación de remitos.
        /// </summary>
        public static string InvoiceRequestAnnulment {
            get {
                return ResourceManager.GetString("InvoiceRequestAnnulment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a REMITO GENERADO - {0} - {1} - {2} - {3}.
        /// </summary>
        public static string InvoiceStatusApproveTitle {
            get {
                return ResourceManager.GetString("InvoiceStatusApproveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a REMITO RECHAZADO por DAF - {0} - {1} - {2} - {3}.
        /// </summary>
        public static string InvoiceStatusRejectTitle {
            get {
                return ResourceManager.GetString("InvoiceStatusRejectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a REMITO - {0} - {1} - {2} - {3}.
        /// </summary>
        public static string InvoiceStatusSentTitle {
            get {
                return ResourceManager.GetString("InvoiceStatusSentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a REMITO: INICIO PROCESO - {0} - {1} - {2} - {3}.
        /// </summary>
        public static string InvoiceStatusSentTitleToUser {
            get {
                return ResourceManager.GetString("InvoiceStatusSentTitleToUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelación de licencia - {0}.
        /// </summary>
        public static string LicenseCancelledTitle {
            get {
                return ResourceManager.GetString("LicenseCancelledTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recursos que tienen pendiente la entrega de certificado por licencia.
        /// </summary>
        public static string LicenseCertificatePending {
            get {
                return ResourceManager.GetString("LicenseCertificatePending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aprobación de licencia - {0}.
        /// </summary>
        public static string LicenseWorkflowTitle {
            get {
                return ResourceManager.GetString("LicenseWorkflowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Informe de Gestión: {0} {1} {2}.
        /// </summary>
        public static string ManagementReport {
            get {
                return ResourceManager.GetString("ManagementReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proceso Aprobación Orden de Compra - {0} - {1} - {2}.
        /// </summary>
        public static string OcProcessTitle {
            get {
                return ResourceManager.GetString("OcProcessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Facturación de prepagas.
        /// </summary>
        public static string PrepaidClosed {
            get {
                return ResourceManager.GetString("PrepaidClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Facturación de prepagas - Importación.
        /// </summary>
        public static string PrepaidImported {
            get {
                return ResourceManager.GetString("PrepaidImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Orden de Compra CONSUMIDA - {0}.
        /// </summary>
        public static string PurchaseOrderConsumed {
            get {
                return ResourceManager.GetString("PurchaseOrderConsumed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accesos a datos sensibles del informe de Gestión.
        /// </summary>
        public static string SensibleData {
            get {
                return ResourceManager.GetString("SensibleData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SOLFAC - COBRADA - {0} - {1} - {2} - {3}.
        /// </summary>
        public static string SolfacStatusAmountCashedTitle {
            get {
                return ResourceManager.GetString("SolfacStatusAmountCashedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SOLFAC - FACTURADA - {0} - {1} - {2} - {3}.
        /// </summary>
        public static string SolfacStatusInvoicedTitle {
            get {
                return ResourceManager.GetString("SolfacStatusInvoicedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SOLFAC - APROBADA por Control de Gestión - {0} - {1} - {2} - {3}.
        /// </summary>
        public static string SolfacStatusInvoicePendingTitle {
            get {
                return ResourceManager.GetString("SolfacStatusInvoicePendingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SOLFAC - RECHAZADA por Control de Gestión - {0} - {1} - {2} - {3}.
        /// </summary>
        public static string SolfacStatusManagementControlRejectedTitle {
            get {
                return ResourceManager.GetString("SolfacStatusManagementControlRejectedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SOLFAC - {0} - {1} - {2} - {3}.
        /// </summary>
        public static string SolfacStatusPendingByManagementControlTitle {
            get {
                return ResourceManager.GetString("SolfacStatusPendingByManagementControlTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SOLFAC: INICIO PROCESO - {0} - {1} - {2} - {3}.
        /// </summary>
        public static string SolfacStatusPendingByManagementControlTitleToUser {
            get {
                return ResourceManager.GetString("SolfacStatusPendingByManagementControlTitleToUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SOLFAC - RECHAZADA por Dirección de Administración y Finanzas - {0} - {1} - {2} - {3}.
        /// </summary>
        public static string SolfacStatusRejectedByDafTitle {
            get {
                return ResourceManager.GetString("SolfacStatusRejectedByDafTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitud de Adelanto - {0}.
        /// </summary>
        public static string WorkflowNotificationAdvancement {
            get {
                return ResourceManager.GetString("WorkflowNotificationAdvancement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitud de Reintegro - {0}.
        /// </summary>
        public static string WorkflowNotificationRefund {
            get {
                return ResourceManager.GetString("WorkflowNotificationRefund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Horas Rechazadas - {0}.
        /// </summary>
        public static string WorkTimeReject {
            get {
                return ResourceManager.GetString("WorkTimeReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Horas pendientes de aprobación - {0}.
        /// </summary>
        public static string WorkTimeSendHours {
            get {
                return ResourceManager.GetString("WorkTimeSendHours", resourceCulture);
            }
        }
    }
}
