//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sofco.Resources.Mails {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MailMessageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal MailMessageResource() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sofco.Resources.Mails.MailMessageResource", typeof(MailMessageResource).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Estimados, &lt;/br&gt;&lt;/br&gt; Se dio de alta la analítica &lt;strong&gt;{0}&lt;/strong&gt;, puede acceder a la misma desde el siguiente &lt;a href=&apos;{1}&apos; target=&apos;_blank&apos;&gt;link&lt;/a&gt;&lt;/br&gt;&lt;/br&gt; Saludos.
        /// </summary>
        public static string AddAnalytic {
            get {
                return ResourceManager.GetString("AddAnalytic", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Estimados, &lt;/br&gt;&lt;/br&gt;Se ha dado el cierre de la analítica &lt;strong&gt;{0}&lt;/strong&gt;, del servicio &lt;strong&gt;{1}&lt;/strong&gt; &lt;/br&gt;&lt;/br&gt;
        ///Saludos.
        /// </summary>
        public static string CloseAnalytic {
            get {
                return ResourceManager.GetString("CloseAnalytic", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to El recurso &lt;strong&gt;{0}&lt;/strong&gt; ha informado a &lt;strong&gt;{1}&lt;/strong&gt; la solicitud de desvinculación de la empresa, a partir del dia {2} &lt;br/&gt;&lt;br/&gt;.
        /// </summary>
        public static string EmployeeEndNotification {
            get {
                return ResourceManager.GetString("EmployeeEndNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Existen novedades que necesitan su confirmacion, por favor acceder a la lista a traves del siguiente &lt;a href=&apos;{0}&apos; target=&apos;_blank&apos;&gt;link&lt;/a&gt;&lt;br/&gt;&lt;br/&gt;.
        /// </summary>
        public static string EmployeeNews {
            get {
                return ResourceManager.GetString("EmployeeNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to RRHH, Autorizador, Recuros: &lt;/br&gt;
        ///Se ha &lt;strong&gt; Aprobado &lt;/strong&gt; la siguiente solicitud de licencia &lt;a href=&apos;{0}&apos; target=&apos;_blank&apos;&gt;link&lt;/a&gt;.
        ///.
        /// </summary>
        public static string LicenseApproveMessage {
            get {
                return ResourceManager.GetString("LicenseApproveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to RRHH: &lt;/br&gt;
        ///Se ha &lt;strong&gt; Aprobado &lt;/strong&gt; la siguiente solicitud de licencia &lt;a href=&apos;{0}&apos; target=&apos;_blank&apos;&gt;link&lt;/a&gt;. Corroborar la documentación necesaria para aprobar la misma.
        ///&lt;/br&gt;&lt;/br&gt;
        ///Recurso: &lt;/br&gt;
        ///La licencia solicitada ha sido &lt;strong&gt; Aprobada &lt;/strong&gt;, si necesita adjuntar documentación a la misma, realícelo desde el siguiente &lt;a href=&apos;{0}&apos; target=&apos;_blank&apos;&gt;link&lt;/a&gt;, recuerde presentar el original a RRHH..
        /// </summary>
        public static string LicenseApprovePendingMessage {
            get {
                return ResourceManager.GetString("LicenseApprovePendingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to RRHH: &lt;/br&gt;
        ///Se ha iniciado el proceso de aprobación de la siguiente solicitud de licencia &lt;a href=&apos;{0}&apos; target=&apos;_blank&apos;&gt;link&lt;/a&gt;.&lt;/br&gt;&lt;/br&gt;
        ///Autorizador: &lt;/br&gt;
        ///El recurso: {1}, ha iniciado un proceso de autorización de licencia. Para autorizarla ingrese al siguiente  &lt;a href=&apos;{0}&apos; target=&apos;_blank&apos;&gt;link&lt;/a&gt;..
        /// </summary>
        public static string LicenseAuthPendingMessage {
            get {
                return ResourceManager.GetString("LicenseAuthPendingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to RRHH: &lt;/br&gt;
        ///Se ha &lt;strong&gt; Autorizado&lt;/strong&gt; la siguiente solicitud de licencia &lt;a href=&apos;{0}&apos; target=&apos;_blank&apos;&gt;link&lt;/a&gt;. Corroborar la documentación necesaria para aprobar la misma.
        ///&lt;/br&gt;&lt;/br&gt;
        ///Recurso: &lt;/br&gt;
        ///La licencia solicitada ha sido &lt;strong&gt; Autorizada&lt;/strong&gt;, si necesita adjuntar documentación a la misma, realícelo desde el siguiente &lt;a href=&apos;{0}&apos; target=&apos;_blank&apos;&gt;link&lt;/a&gt;..
        /// </summary>
        public static string LicensePendingMessage {
            get {
                return ResourceManager.GetString("LicensePendingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to RRHH: &lt;/br&gt;
        ///Se ha &lt;strong&gt; Rechazado&lt;/strong&gt; la siguiente solicitud de licencia &lt;a href=&apos;{0}&apos; target=&apos;_blank&apos;&gt;link&lt;/a&gt;.
        ///Motivo: {1}
        ///&lt;/br&gt;&lt;/br&gt;
        ///Recurso: &lt;/br&gt;
        ///La licencia solicitada ha sido &lt;strong&gt; Rechazada&lt;/strong&gt;. Acceso a la licencia desde este &lt;a href=&apos;{0}&apos; target=&apos;_blank&apos;&gt;link&lt;/a&gt;.
        ///Motivo: {1}.
        /// </summary>
        public static string LicenseRejectMessage {
            get {
                return ResourceManager.GetString("LicenseRejectMessage", resourceCulture);
            }
        }
    }
}
