//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sofco.Resources.Billing {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Invoice {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Invoice() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sofco.Resources.Billing.Invoice", typeof(Invoice).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to billing/invoice.approved.
        /// </summary>
        public static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to billing/invoice.cancelled.
        /// </summary>
        public static string Cancelled {
            get {
                return ResourceManager.GetString("Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to billing/invoice.cannotApprove.
        /// </summary>
        public static string CannotApprove {
            get {
                return ResourceManager.GetString("CannotApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to billing/invoice.cannotDelete.
        /// </summary>
        public static string CannotDelete {
            get {
                return ResourceManager.GetString("CannotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to billing/invoice.cannotReject.
        /// </summary>
        public static string CannotReject {
            get {
                return ResourceManager.GetString("CannotReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to billing/invoice.cannotSendToDaf.
        /// </summary>
        public static string CannotSendToDaf {
            get {
                return ResourceManager.GetString("CannotSendToDaf", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Nota de Crédito - .
        /// </summary>
        public static string CrmPrefixCreditNoteTitle {
            get {
                return ResourceManager.GetString("CrmPrefixCreditNoteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Nota de Débito - .
        /// </summary>
        public static string CrmPrefixDebitNoteTitle {
            get {
                return ResourceManager.GetString("CrmPrefixDebitNoteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to billing/invoice.deleted.
        /// </summary>
        public static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to billing/invoice.descriptionRequired.
        /// </summary>
        public static string DescriptionRequired {
            get {
                return ResourceManager.GetString("DescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to billing/invoice.detailsRequired.
        /// </summary>
        public static string DetailsRequired {
            get {
                return ResourceManager.GetString("DetailsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to billing/invoice.excelUpload.
        /// </summary>
        public static string ExcelUpload {
            get {
                return ResourceManager.GetString("ExcelUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to billing/invoice.invoiceCreated.
        /// </summary>
        public static string InvoiceCreated {
            get {
                return ResourceManager.GetString("InvoiceCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to billing/invoice.invoiceNumerAlreadyExist.
        /// </summary>
        public static string InvoiceNumerAlreadyExist {
            get {
                return ResourceManager.GetString("InvoiceNumerAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to billing/invoice.invoiceNumerRequired.
        /// </summary>
        public static string InvoiceNumerRequired {
            get {
                return ResourceManager.GetString("InvoiceNumerRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to billing/invoice.needExcelToSend.
        /// </summary>
        public static string NeedExcelToSend {
            get {
                return ResourceManager.GetString("NeedExcelToSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to billing/invoice.needPdfToApprove.
        /// </summary>
        public static string NeedPdfToApprove {
            get {
                return ResourceManager.GetString("NeedPdfToApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to billing/invoice.notFound.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to billing/invoice.notFounds.
        /// </summary>
        public static string NotFounds {
            get {
                return ResourceManager.GetString("NotFounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to billing/invoice.pdfUpload.
        /// </summary>
        public static string PdfUpload {
            get {
                return ResourceManager.GetString("PdfUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to billing/invoice.quantityRequired.
        /// </summary>
        public static string QuantityRequired {
            get {
                return ResourceManager.GetString("QuantityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to billing/invoice.reject.
        /// </summary>
        public static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to billing/invoice.sentToDaf.
        /// </summary>
        public static string SentToDaf {
            get {
                return ResourceManager.GetString("SentToDaf", resourceCulture);
            }
        }
    }
}
