CREATE OR ALTER VIEW qv.AnalyticsView AS
	[Id]
	,[ActivityId]
	,[ClientExternalId]
	,[ClientExternalName]
	,[ClientGroupId]
	,[CreationDate]
	,[SectorId]
	,[EndDateContract]
	,[ManagerId]
	,[Name]
	,[Proposal]
	,[Service]
	,[SolutionId]
	,[StartDateContract]
	,[Status]
	,[TechnologyId]
	,[Title]
	,[UsersQv]
	,[CostCenterId]
	,[TitleId]
	,[SoftwareLawId]
	,[ServiceTypeId]
	,[CommercialManagerId]
	,[ServiceId]
  FROM [app].[Analytics]