
INSERT INTO [app].[EmployeeProfile] ([Text]) VALUES ('Administración de Personal')
INSERT INTO [app].[EmployeeProfile] ([Text]) VALUES ('Administrador de Base de Datos')
INSERT INTO [app].[EmployeeProfile] ([Text]) VALUES ('Administrador de Redes, Comunicaciones y Seguridad / Administrador de red')
INSERT INTO [app].[EmployeeProfile] ([Text]) VALUES ('Administrador de Redes, Comunicaciones y Sistemas Operativos / Administrador de red')
INSERT INTO [app].[EmployeeProfile] ([Text]) VALUES ('Administrativo Operativo y Tecnología')
INSERT INTO [app].[EmployeeProfile] ([Text]) VALUES ('Analista Contable / Impositivo / Administrativo / Legales')
INSERT INTO [app].[EmployeeProfile] ([Text]) VALUES ('Analista de Calidad')
INSERT INTO [app].[EmployeeProfile] ([Text]) VALUES ('Analista de Gestión Operativa (GO)')
INSERT INTO [app].[EmployeeProfile] ([Text]) VALUES ('Analista de Marketing')
INSERT INTO [app].[EmployeeProfile] ([Text]) VALUES ('Analista de Planificación Presupuestaria')
INSERT INTO [app].[EmployeeProfile] ([Text]) VALUES ('Analista de Recursos Humanos')
INSERT INTO [app].[EmployeeProfile] ([Text]) VALUES ('Analista de Seguimiento de Proyectos')
INSERT INTO [app].[EmployeeProfile] ([Text]) VALUES ('Analista de Sistemas / Analista funcional')
INSERT INTO [app].[EmployeeProfile] ([Text]) VALUES ('Analista Técnico')
INSERT INTO [app].[EmployeeProfile] ([Text]) VALUES ('Arquitecto')
INSERT INTO [app].[EmployeeProfile] ([Text]) VALUES ('Asistente')
INSERT INTO [app].[EmployeeProfile] ([Text]) VALUES ('Cadete')
INSERT INTO [app].[EmployeeProfile] ([Text]) VALUES ('Capacitación')
INSERT INTO [app].[EmployeeProfile] ([Text]) VALUES ('Desarrollador')
INSERT INTO [app].[EmployeeProfile] ([Text]) VALUES ('Director Comercial')
INSERT INTO [app].[EmployeeProfile] ([Text]) VALUES ('Director de Administración y Finanzas')
INSERT INTO [app].[EmployeeProfile] ([Text]) VALUES ('Director de Negocios Corporativos')
INSERT INTO [app].[EmployeeProfile] ([Text]) VALUES ('Director de Servicios IT y Soluciones IT')
INSERT INTO [app].[EmployeeProfile] ([Text]) VALUES ('Director General')
INSERT INTO [app].[EmployeeProfile] ([Text]) VALUES ('Diseñador Gráfico Web')
INSERT INTO [app].[EmployeeProfile] ([Text]) VALUES ('Diseñador UX')
INSERT INTO [app].[EmployeeProfile] ([Text]) VALUES ('Especialista en Seguridad de Aplicaciones')
INSERT INTO [app].[EmployeeProfile] ([Text]) VALUES ('Especialista Tecnológico')
INSERT INTO [app].[EmployeeProfile] ([Text]) VALUES ('Gerente Comercial')
INSERT INTO [app].[EmployeeProfile] ([Text]) VALUES ('Gerente de Administración y Finanzas / Gerente de área')
INSERT INTO [app].[EmployeeProfile] ([Text]) VALUES ('Gerente de Cuentas')
INSERT INTO [app].[EmployeeProfile] ([Text]) VALUES ('Gerente de División Tecnología / Gerente de área')
INSERT INTO [app].[EmployeeProfile] ([Text]) VALUES ('Gerente de Gobierno Corporativo, Aseguramiento de Calidad y Compliance')
INSERT INTO [app].[EmployeeProfile] ([Text]) VALUES ('Gerente de Legales / Gerente de área')
INSERT INTO [app].[EmployeeProfile] ([Text]) VALUES ('Gerente de Negocios Tecnología')
INSERT INTO [app].[EmployeeProfile] ([Text]) VALUES ('Gerente de Planificación Presupuestaria')
INSERT INTO [app].[EmployeeProfile] ([Text]) VALUES ('Gerente de Preventa / Gerente de área')
INSERT INTO [app].[EmployeeProfile] ([Text]) VALUES ('Gerente de Proyecto o Comunidades')
INSERT INTO [app].[EmployeeProfile] ([Text]) VALUES ('Gerente de Recursos Humanos / Gerente de área')
INSERT INTO [app].[EmployeeProfile] ([Text]) VALUES ('Gerente de Relaciones Institucionales y Logística / Gerente de área')
INSERT INTO [app].[EmployeeProfile] ([Text]) VALUES ('Junior')
INSERT INTO [app].[EmployeeProfile] ([Text]) VALUES ('Líder de Área Staff')
INSERT INTO [app].[EmployeeProfile] ([Text]) VALUES ('Líder de Comunidades')
INSERT INTO [app].[EmployeeProfile] ([Text]) VALUES ('Líder de Proyecto')
INSERT INTO [app].[EmployeeProfile] ([Text]) VALUES ('Líder de Proyecto de Tecnología')
INSERT INTO [app].[EmployeeProfile] ([Text]) VALUES ('Marketing Estratégico y Alianzas')
INSERT INTO [app].[EmployeeProfile] ([Text]) VALUES ('Operador')
INSERT INTO [app].[EmployeeProfile] ([Text]) VALUES ('Recepcionista')
INSERT INTO [app].[EmployeeProfile] ([Text]) VALUES ('Responsable de comunicación externa')
INSERT INTO [app].[EmployeeProfile] ([Text]) VALUES ('Selección')
INSERT INTO [app].[EmployeeProfile] ([Text]) VALUES ('Semi Senior')
INSERT INTO [app].[EmployeeProfile] ([Text]) VALUES ('Senior')
INSERT INTO [app].[EmployeeProfile] ([Text]) VALUES ('Sistemas, Redes y Tecnología Interna / Administrador de red')
INSERT INTO [app].[EmployeeProfile] ([Text]) VALUES ('Soporte Técnico')
INSERT INTO [app].[EmployeeProfile] ([Text]) VALUES ('Técnico en Telecomunicaciones')
INSERT INTO [app].[EmployeeProfile] ([Text]) VALUES ('Tester')
