

INSERT INTO [app].[CostDetailTypes] VALUES  ('% Ajuste', 1)
INSERT INTO [app].[CostDetailTypes] VALUES  ('Recupero Vacaciones', 1)
INSERT INTO [app].[CostDetailTypes] VALUES  ('Gratificaciones', 1)
INSERT INTO [app].[CostDetailTypes] VALUES  ('Riesgo/Retenciones', 1)
INSERT INTO [app].[CostDetailTypes] VALUES ('Estudio prestaciones y subcontratados', 0)
INSERT INTO [app].[CostDetailTypes] VALUES ('Hardware y Software (no incluye amortizaciones)', 0)
INSERT INTO [app].[CostDetailTypes] VALUES ('Viáticos', 0)
INSERT INTO [app].[CostDetailTypes] VALUES ('Teléfono', 0)
INSERT INTO [app].[CostDetailTypes] VALUES ('Correo', 0)
INSERT INTO [app].[CostDetailTypes] VALUES ('Gastos vehículos', 0)
INSERT INTO [app].[CostDetailTypes] VALUES ('Capacitación', 0)
INSERT INTO [app].[CostDetailTypes] VALUES ('Seguros (caución - transporte etc para DWDM)', 0)
INSERT INTO [app].[CostDetailTypes] VALUES ('Compra Materiales (Nac, Importados + Importaciones)', 0)
INSERT INTO [app].[CostDetailTypes] VALUES ('Otros', 0)
INSERT INTO [app].[CostDetailTypes] VALUES ('Amortizaciones', 0)
INSERT INTO [app].[CostDetailTypes] VALUES ('Recursos', 0)
INSERT INTO [app].[CostDetailTypes] VALUES ('Perfiles', 0)