INSERT INTO [app].[CostDetailCategories] ([Name]) VALUES ('Sueldos')
INSERT INTO [app].[CostDetailCategories] ([Name]) VALUES ('Viáticos')
INSERT INTO [app].[CostDetailCategories] ([Name]) VALUES ('Gastos Vehículos')
INSERT INTO [app].[CostDetailCategories] ([Name]) VALUES ('Edificio')
INSERT INTO [app].[CostDetailCategories] ([Name]) VALUES ('Seguros')
INSERT INTO [app].[CostDetailCategories] ([Name]) VALUES ('Servicios')
INSERT INTO [app].[CostDetailCategories] ([Name]) VALUES ('Muebles y útiles')
INSERT INTO [app].[CostDetailCategories] ([Name]) VALUES ('Hardware y Software')
INSERT INTO [app].[CostDetailCategories] ([Name]) VALUES ('Capacitación')
INSERT INTO [app].[CostDetailCategories] ([Name]) VALUES ('Honorarios ')
INSERT INTO [app].[CostDetailCategories] ([Name]) VALUES ('Gastos reclutamiento personal')
INSERT INTO [app].[CostDetailCategories] ([Name]) VALUES ('Red')
INSERT INTO [app].[CostDetailCategories] ([Name]) VALUES ('Infraestructura')