INSERT INTO [app].[CostDetailCategories] ([Name], [BelongEmployee], [Default]) VALUES ('% Ajuste General', 0, 1)
INSERT INTO [app].[CostDetailCategories] ([Name], [BelongEmployee], [Default]) VALUES ('Capacitación', 0, 0)
INSERT INTO [app].[CostDetailCategories] ([Name], [BelongEmployee], [Default]) VALUES ('Compra Materiales', 0, 0)
INSERT INTO [app].[CostDetailCategories] ([Name], [BelongEmployee], [Default]) VALUES ('Derechos Expo Servicios', 0, 0)
INSERT INTO [app].[CostDetailCategories] ([Name], [BelongEmployee], [Default]) VALUES ('Documentación Gral Técnica', 0, 0)
INSERT INTO [app].[CostDetailCategories] ([Name], [BelongEmployee], [Default]) VALUES ('Edificio', 0, 0)
INSERT INTO [app].[CostDetailCategories] ([Name], [BelongEmployee], [Default]) VALUES ('Gastos Reclutamiento Personal', 0, 0)
INSERT INTO [app].[CostDetailCategories] ([Name], [BelongEmployee], [Default]) VALUES ('Gastos Vehiculos', 0, 0)
INSERT INTO [app].[CostDetailCategories] ([Name], [BelongEmployee], [Default]) VALUES ('Gratificaciones', 1, 0)
INSERT INTO [app].[CostDetailCategories] ([Name], [BelongEmployee], [Default]) VALUES ('Hardware y Software', 0, 0)
INSERT INTO [app].[CostDetailCategories] ([Name], [BelongEmployee], [Default]) VALUES ('Honorarios', 0, 0)
INSERT INTO [app].[CostDetailCategories] ([Name], [BelongEmployee], [Default]) VALUES ('Horas Extras/Guardias Pasivas', 1, 0)
INSERT INTO [app].[CostDetailCategories] ([Name], [BelongEmployee], [Default]) VALUES ('Informe Final', 0, 0)
INSERT INTO [app].[CostDetailCategories] ([Name], [BelongEmployee], [Default]) VALUES ('Infraestructura', 0, 0)
INSERT INTO [app].[CostDetailCategories] ([Name], [BelongEmployee], [Default]) VALUES ('Inscripciones', 0, 0)
INSERT INTO [app].[CostDetailCategories] ([Name], [BelongEmployee], [Default]) VALUES ('Licencias', 0, 0)
INSERT INTO [app].[CostDetailCategories] ([Name], [BelongEmployee], [Default]) VALUES ('Muebles y Útiles', 0, 0)
INSERT INTO [app].[CostDetailCategories] ([Name], [BelongEmployee], [Default]) VALUES ('Prov Costos', 0, 0)
INSERT INTO [app].[CostDetailCategories] ([Name], [BelongEmployee], [Default]) VALUES ('Publicidad, Regalos, Catalogos', 0, 0)
INSERT INTO [app].[CostDetailCategories] ([Name], [BelongEmployee], [Default]) VALUES ('Reasignación de Costos', 0, 0)
INSERT INTO [app].[CostDetailCategories] ([Name], [BelongEmployee], [Default]) VALUES ('Recupero Vacaciones', 1, 0)
INSERT INTO [app].[CostDetailCategories] ([Name], [BelongEmployee], [Default]) VALUES ('Red', 0, 0)
INSERT INTO [app].[CostDetailCategories] ([Name], [BelongEmployee], [Default]) VALUES ('Riesgos/Retenciones', 1, 0)
INSERT INTO [app].[CostDetailCategories] ([Name], [BelongEmployee], [Default]) VALUES ('Seguros', 0, 0)
INSERT INTO [app].[CostDetailCategories] ([Name], [BelongEmployee], [Default]) VALUES ('Servicios', 0, 0)
INSERT INTO [app].[CostDetailCategories] ([Name], [BelongEmployee], [Default]) VALUES ('Viáticos', 0, 0)
INSERT INTO [app].[CostDetailCategories] ([Name], [BelongEmployee], [Default]) VALUES ('Recursos', 0, 0)
INSERT INTO [app].[CostDetailCategories] ([Name], [BelongEmployee], [Default]) VALUES ('Perfiles', 0, 0)