DECLARE @IdAjuste INT = (select Id from [app].[CostDetailCategories] where Name = '% Ajuste General')
DECLARE @IdCapacitacion INT = (select Id from [app].[CostDetailCategories] where Name = 'Capacitación')
DECLARE @IdCompraMateriales INT = (select Id from [app].[CostDetailCategories] where Name = 'Compra Materiales')
DECLARE @IdExpo INT = (select Id from [app].[CostDetailCategories] where Name = 'Derechos Expo Servicios')
DECLARE @IdDocTecnica INT = (select Id from [app].[CostDetailCategories] where Name = 'Documentación Gral Técnica')
DECLARE @IdEdificio INT = (select Id from [app].[CostDetailCategories] where Name = 'Edificio')
DECLARE @IdRecPersonal INT = (select Id from [app].[CostDetailCategories] where Name = 'Gastos Reclutamiento Personal')
DECLARE @IdVehiculos INT = (select Id from [app].[CostDetailCategories] where Name = 'Gastos Vehiculos')
DECLARE @IdGratificaciones INT = (select Id from [app].[CostDetailCategories] where Name = 'Gratificaciones')
DECLARE @IdHardwareSoftware INT = (select Id from [app].[CostDetailCategories] where Name = 'Hardware y Software')
DECLARE @IdHonorarios INT = (select Id from [app].[CostDetailCategories] where Name = 'Honorarios')
DECLARE @IdHsExtras INT = (select Id from [app].[CostDetailCategories] where Name = 'Horas Extras/Guardias Pasivas')
DECLARE @IdInformeFinal INT = (select Id from [app].[CostDetailCategories] where Name = 'Informe Final')
DECLARE @IdInfraestructura INT = (select Id from [app].[CostDetailCategories] where Name = 'Infraestructura')
DECLARE @IdInscripciones INT = (select Id from [app].[CostDetailCategories] where Name = 'Inscripciones')
DECLARE @IdLicencias INT = (select Id from [app].[CostDetailCategories] where Name = 'Licencias')
DECLARE @IdMuebles INT = (select Id from [app].[CostDetailCategories] where Name = 'Muebles y Útiles')
DECLARE @IdProv INT = (select Id from [app].[CostDetailCategories] where Name = 'Prov Costos')
DECLARE @IdPublicidad INT = (select Id from [app].[CostDetailCategories] where Name = 'Publicidad, Regalos, Catalogos')
DECLARE @IdReasignacion INT = (select Id from [app].[CostDetailCategories] where Name = 'Reasignación de Costos')
DECLARE @IdRecupero INT = (select Id from [app].[CostDetailCategories] where Name = 'Recupero Vacaciones')
DECLARE @IdRed INT = (select Id from [app].[CostDetailCategories] where Name = 'Red')
DECLARE @IdRiesgos INT = (select Id from [app].[CostDetailCategories] where Name = 'Riesgos/Retenciones')
DECLARE @IdSeguros INT = (select Id from [app].[CostDetailCategories] where Name = 'Seguros')
DECLARE @IdServicios INT = (select Id from [app].[CostDetailCategories] where Name = 'Servicios')
DECLARE @IdViaticos INT = (select Id from [app].[CostDetailCategories] where Name = 'Viáticos')

INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId], [Codigo]) VALUES ('% Ajuste General',@IdAjuste,'')
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId], [Codigo]) VALUES ('Capacitacion/Formacion',@IdCapacitacion,'633000')
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId], [Codigo]) VALUES ('Compra Materiales Equipos Trab',@IdCompraMateriales,'605000')
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId], [Codigo]) VALUES ('Importaciones',@IdCompraMateriales,'609000')
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId], [Codigo]) VALUES ('Derechos Expo Servicios',@IdExpo,'635180')
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId], [Codigo]) VALUES ('Documentacion Gral Tecnica',@IdDocTecnica,'618100')
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId], [Codigo]) VALUES ('Alquiler - Expensas - Limpieza',@IdEdificio,'613200')
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId], [Codigo]) VALUES ('Reparacion Y Conservacion De Bienes Inmuebles',@IdEdificio,'615200')
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId], [Codigo]) VALUES ('Gastos Reclutamiento Personal',@IdRecPersonal,'628400')
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId], [Codigo]) VALUES ('Combustible',@IdVehiculos,'606200')
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId], [Codigo]) VALUES ('Patentes/Impuestos A Los Vehiculos',@IdVehiculos,'635140')
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId], [Codigo]) VALUES ('Seguro Rodados',@IdVehiculos,'616500')
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId], [Codigo]) VALUES ('Conservacion Reparacion De Rodados',@IdVehiculos,'615600')
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId], [Codigo]) VALUES ('Amortizacion Rodados',@IdVehiculos,'681250')
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId], [Codigo]) VALUES ('Gratificaciones',@IdGratificaciones,'')
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId], [Codigo]) VALUES ('Hardware Tii',@IdHardwareSoftware,'615700')
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId], [Codigo]) VALUES ('Mantenimiento De Equipos',@IdHardwareSoftware,'615900')
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId], [Codigo]) VALUES ('Mantenimiento De Software',@IdHardwareSoftware,'615800')
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId], [Codigo]) VALUES ('Amortizacion De  Materiales De  Informatica',@IdHardwareSoftware,'681320')
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId], [Codigo]) VALUES ('Honorarios ',@IdHonorarios,'622000')
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId], [Codigo]) VALUES ('Honorarios Fiscales',@IdHonorarios,'622001')
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId], [Codigo]) VALUES ('Honor Auditoria',@IdHonorarios,'622002')
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId], [Codigo]) VALUES ('Horas Extras/Guardias Pasivas',@IdHsExtras,'')
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId], [Codigo]) VALUES ('Otros Gastos Bancarios',@IdInformeFinal,'627020')
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId], [Codigo]) VALUES ('Comisiones Bancarias',@IdInformeFinal,'627030')
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId], [Codigo]) VALUES ('Otros Impuestos Y Tasas',@IdInformeFinal,'635000')
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId], [Codigo]) VALUES ('Multas',@IdInformeFinal,'635100')
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId], [Codigo]) VALUES ('Impuestos Sellos',@IdInformeFinal,'635110')
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId], [Codigo]) VALUES ('Impuesto A Las Ganancias',@IdInformeFinal,'635160')
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId], [Codigo]) VALUES ('Ingresos Brutos',@IdInformeFinal,'635300')
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId], [Codigo]) VALUES ('7% Gs. Audit. Ley Software - Re',@IdInformeFinal,'635600')
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId], [Codigo]) VALUES ('Regalias',@IdInformeFinal,'658100')
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId], [Codigo]) VALUES ('Regalias Retencion',@IdInformeFinal,'658105')
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId], [Codigo]) VALUES ('Intereses Por Deudas Diversas',@IdInformeFinal,'661000')
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId], [Codigo]) VALUES ('Impuesto Ctas Ctes',@IdInformeFinal,'661510')
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId], [Codigo]) VALUES ('Diferencia De Cambio',@IdInformeFinal,'666000')
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId], [Codigo]) VALUES ('Provision Regalias Sede',@IdInformeFinal,'689030')
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId], [Codigo]) VALUES ('Retencion Fuente Marca',@IdInformeFinal,'')
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId], [Codigo]) VALUES ('Infraestructura',@IdInfraestructura,'')
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId], [Codigo]) VALUES ('Inscripciones',@IdInscripciones,'635500')
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId], [Codigo]) VALUES ('Compra De Licencias/Costos',@IdLicencias,'604040')
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId], [Codigo]) VALUES ('Fotocopias',@IdMuebles,'611400')
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId], [Codigo]) VALUES ('Proveedores Articulos De Oficina',@IdMuebles,'606400')
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId], [Codigo]) VALUES ('Otros Proveedores Y Material',@IdMuebles,'606800')
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId], [Codigo]) VALUES ('Correo Y Mensajeria',@IdMuebles,'626200')
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId], [Codigo]) VALUES ('Amortiz Materiales De Oficina',@IdMuebles,'681100')
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId], [Codigo]) VALUES ('Amortizacion Muebles',@IdMuebles,'681400')
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId], [Codigo]) VALUES ('Prov Costos',@IdProv,'604011')
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId], [Codigo]) VALUES ('Publicidad,Regalos,Catalogos',@IdPublicidad,'623000')
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId], [Codigo]) VALUES ('Reasignacion De Costos',@IdReasignacion,'601000')
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId], [Codigo]) VALUES ('Recupero Vacaciones',@IdRecupero,'')
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId], [Codigo]) VALUES ('Red',@IdRed,'')
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId], [Codigo]) VALUES ('Riesgos/Retenciones',@IdRiesgos,'')
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId], [Codigo]) VALUES ('Accidentes Personales',@IdSeguros,'616250')
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId], [Codigo]) VALUES ('Multiriesgo',@IdSeguros,'616100')
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId], [Codigo]) VALUES ('Responsabilidad Civil',@IdSeguros,'616700')
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId], [Codigo]) VALUES ('Caucion',@IdSeguros,'616600')
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId], [Codigo]) VALUES ('Seguro De Transporte Terrestre',@IdSeguros,'616900')
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId], [Codigo]) VALUES ('Agua-Luz-Gas',@IdServicios,'606100')
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId], [Codigo]) VALUES ('Telecom Argentina/Philips',@IdServicios,'626100')
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId], [Codigo]) VALUES ('Celulares, Nextel, Otros',@IdServicios,'626100')
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId], [Codigo]) VALUES ('Gastos Reuniones Seminarios',@IdViaticos ,'618500')
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId], [Codigo]) VALUES ('Recepciones',@IdViaticos ,'625700')
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId], [Codigo]) VALUES ('Taxi, Peaje Y Estacionamiento',@IdViaticos ,'625510')
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId], [Codigo]) VALUES ('Viajes Y Traslados',@IdViaticos ,'625100')
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId], [Codigo]) VALUES ('Otros Gastos Ligados Misiones',@IdViaticos ,'625600')
