
DECLARE @IdSueldo INT = (select Id from [app].[CostDetailCategories] where Name = 'Sueldos')
DECLARE @IdViaticos INT = (select Id from [app].[CostDetailCategories] where Name = 'Viáticos')
DECLARE @IdVehiculos INT = (select Id from [app].[CostDetailCategories] where Name = 'Gastos Vehículos')
DECLARE @IdEdificio INT = (select Id from [app].[CostDetailCategories] where Name = 'Edificio')
DECLARE @IdSeguros INT = (select Id from [app].[CostDetailCategories] where Name = 'Seguros')
DECLARE @IdServicios INT = (select Id from [app].[CostDetailCategories] where Name = 'Servicios')
DECLARE @IdMuebles INT = (select Id from [app].[CostDetailCategories] where Name = 'Muebles y útiles')
DECLARE @IdHardware INT = (select Id from [app].[CostDetailCategories] where Name = 'Hardware y Software')
DECLARE @IdCapacitacion INT = (select Id from [app].[CostDetailCategories] where Name = 'Capacitación')
DECLARE @IdHonorarios INT = (select Id from [app].[CostDetailCategories] where Name = 'Honorarios')
DECLARE @IdPersonal INT = (select Id from [app].[CostDetailCategories] where Name = 'Gastos reclutamiento personal')	
DECLARE @IdRed INT = (select Id from [app].[CostDetailCategories] where Name = 'Red')
DECLARE @IdInfra INT = (select Id from [app].[CostDetailCategories] where Name = 'Infraestructura')


INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId]) VALUES ('Sueldos - Honorarios - Pasantías', @IdSueldo)
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId]) VALUES ('Viajes y Traslados', @IdViaticos)
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId]) VALUES ('Otros gastos ligados a Misiones', @IdViaticos)
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId]) VALUES ('Taxi, peaje y estacionamiento', @IdViaticos)
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId]) VALUES ('Recepciones', @IdViaticos)
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId]) VALUES ('Amortización Rodados', @IdVehiculos)
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId]) VALUES ('Combustible', @IdVehiculos)
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId]) VALUES ('Conservación y reparación de rodados', @IdVehiculos)
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId]) VALUES ('Patentes', @IdVehiculos)
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId]) VALUES ('Seguro Rodados', @IdVehiculos)
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId]) VALUES ('Alquiler - Expensas - Limpieza', @IdEdificio)
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId]) VALUES ('Reparación y conservación de bienes inmuebles', @IdEdificio)
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId]) VALUES ('Amortizaciones instalaciones general', @IdEdificio)
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId]) VALUES ('Multiriesgo', @IdSeguros)
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId]) VALUES ('Seguro Vida Obligatorio', @IdSeguros)
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId]) VALUES ('Responsabilidad civil', @IdSeguros)
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId]) VALUES ('Caución', @IdSeguros)
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId]) VALUES ('Agua - Luz - Gas', @IdServicios)
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId]) VALUES ('Telecom Argentina / Phillips', @IdServicios)
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId]) VALUES ('Celulares, Nextel y otros', @IdServicios)
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId]) VALUES ('Amortización de muebles', @IdMuebles)
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId]) VALUES ('Reparación y conservación de mobiliarios', @IdMuebles)
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId]) VALUES ('Amortización materiales de oficina', @IdMuebles)
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId]) VALUES ('Proveedores artículos de oficina', @IdMuebles)
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId]) VALUES ('Otros proveedores y materiales', @IdMuebles)
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId]) VALUES ('Fotocopias', @IdMuebles)
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId]) VALUES ('Correo', @IdMuebles)
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId]) VALUES ('Amortización materiales informática', @IdHardware)
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId]) VALUES ('Amortización de Software', @IdHardware)
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId]) VALUES ('Hardware TII', @IdHardware)
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId]) VALUES ('Mantenimiento de software', @IdHardware)
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId]) VALUES ('Mantenimiento de equipos', @IdHardware)
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId]) VALUES ('Capacitación', @IdCapacitacion)
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId]) VALUES ('Honorarios', @IdHonorarios)  
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId]) VALUES ('Gastos reclutamiento personal', @IdPersonal) 
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId]) VALUES ('Red', @IdRed) 
INSERT INTO [app].[CostDetailSubcategories] ([Name], [CostDetailCategoryId]) VALUES ('Infraestructura', @IdInfra)


GO


