// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore.Migrations;

namespace Sofco.WebApi.Migrations
{
    public partial class WorkTimeApprovalAnalytic : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "ServiceId",
                schema: "app",
                table: "WorkTimeApprovals");

            migrationBuilder.AddColumn<int>(
                name: "AnalyticId",
                schema: "app",
                table: "WorkTimeApprovals",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.CreateIndex(
                name: "IX_WorkTimeApprovals_AnalyticId_EmployeeId_ApprovalUserId",
                schema: "app",
                table: "WorkTimeApprovals",
                columns: new[] { "AnalyticId", "EmployeeId", "ApprovalUserId" },
                unique: true);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_WorkTimeApprovals_AnalyticId_EmployeeId_ApprovalUserId",
                schema: "app",
                table: "WorkTimeApprovals");

            migrationBuilder.DropColumn(
                name: "AnalyticId",
                schema: "app",
                table: "WorkTimeApprovals");

            migrationBuilder.AddColumn<Guid>(
                name: "ServiceId",
                schema: "app",
                table: "WorkTimeApprovals",
                nullable: false,
                defaultValue: new Guid("00000000-0000-0000-0000-000000000000"));
        }
    }
}
