// <auto-generated/>
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore.Migrations;

namespace Sofco.WebApi.Migrations
{
    public partial class UpdateEmployeeAddress : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "Address",
                schema: "app",
                table: "Employees",
                maxLength: 400,
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "Country",
                schema: "app",
                table: "Employees",
                maxLength: 200,
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "HealthInsuranceCode",
                schema: "app",
                table: "Employees",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<string>(
                name: "Location",
                schema: "app",
                table: "Employees",
                maxLength: 200,
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "PrepaidHealthCode",
                schema: "app",
                table: "Employees",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<string>(
                name: "Province",
                schema: "app",
                table: "Employees",
                maxLength: 200,
                nullable: true);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "Address",
                schema: "app",
                table: "Employees");

            migrationBuilder.DropColumn(
                name: "Country",
                schema: "app",
                table: "Employees");

            migrationBuilder.DropColumn(
                name: "HealthInsuranceCode",
                schema: "app",
                table: "Employees");

            migrationBuilder.DropColumn(
                name: "Location",
                schema: "app",
                table: "Employees");

            migrationBuilder.DropColumn(
                name: "PrepaidHealthCode",
                schema: "app",
                table: "Employees");

            migrationBuilder.DropColumn(
                name: "Province",
                schema: "app",
                table: "Employees");
        }
    }
}
