// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore.Migrations;

namespace Sofco.WebApi.Migrations
{
    public partial class SectorResponsable : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<int>(
                name: "ResponsableUserId",
                schema: "app",
                table: "Sectors",
                nullable: false,
                defaultValue: 1);

            migrationBuilder.CreateIndex(
                name: "IX_Sectors_ResponsableUserId",
                schema: "app",
                table: "Sectors",
                column: "ResponsableUserId");

            migrationBuilder.AddForeignKey(
                name: "FK_Sectors_Users_ResponsableUserId",
                schema: "app",
                table: "Sectors",
                column: "ResponsableUserId",
                principalSchema: "app",
                principalTable: "Users",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Sectors_Users_ResponsableUserId",
                schema: "app",
                table: "Sectors");

            migrationBuilder.DropIndex(
                name: "IX_Sectors_ResponsableUserId",
                schema: "app",
                table: "Sectors");

            migrationBuilder.DropColumn(
                name: "ResponsableUserId",
                schema: "app",
                table: "Sectors");
        }
    }
}
