// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore.Migrations;

namespace Sofco.WebApi.Migrations
{
    public partial class EmployeeAddFields : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<decimal>(
                name: "Cuil",
                schema: "app",
                table: "Employees",
                nullable: false,
                defaultValue: 0m);

            migrationBuilder.AddColumn<int>(
                name: "DocumentNumber",
                schema: "app",
                table: "Employees",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<string>(
                name: "DocumentNumberType",
                schema: "app",
                table: "Employees",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "PhoneAreaCode",
                schema: "app",
                table: "Employees",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<int>(
                name: "PhoneCountryCode",
                schema: "app",
                table: "Employees",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<int>(
                name: "PhoneNumber",
                schema: "app",
                table: "Employees",
                nullable: false,
                defaultValue: 0);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "Cuil",
                schema: "app",
                table: "Employees");

            migrationBuilder.DropColumn(
                name: "DocumentNumber",
                schema: "app",
                table: "Employees");

            migrationBuilder.DropColumn(
                name: "DocumentNumberType",
                schema: "app",
                table: "Employees");

            migrationBuilder.DropColumn(
                name: "PhoneAreaCode",
                schema: "app",
                table: "Employees");

            migrationBuilder.DropColumn(
                name: "PhoneCountryCode",
                schema: "app",
                table: "Employees");

            migrationBuilder.DropColumn(
                name: "PhoneNumber",
                schema: "app",
                table: "Employees");
        }
    }
}
