//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sofco.Resources.AllocationManagement {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    Clase de recurso fuertemente tipada para buscar cadenas localizadas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CostCenter {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal CostCenter() {
        }
        
        /// <summary>
        ///    Devuelve la instancia de ResourceManager en caché que usa la clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sofco.Resources.AllocationManagement.CostCenter", typeof(CostCenter).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Reemplaza la propiedad CurrentUICulture del subproceso actual para todas
        ///    las búsquedas de recursos que usan esta clase de recursos fuertemente tipada.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Busca una cadena localizada similar a allocationManagement/costCenter.codeAlreadyExist.
        /// </summary>
        public static string CodeAlreadyExist {
            get {
                return ResourceManager.GetString("CodeAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena localizada similar a allocationManagement/costCenter.codeIsRequired.
        /// </summary>
        public static string CodeIsRequired {
            get {
                return ResourceManager.GetString("CodeIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena localizada similar a allocationManagement/costCenter.codeWrongLength.
        /// </summary>
        public static string CodeWrongLength {
            get {
                return ResourceManager.GetString("CodeWrongLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena localizada similar a allocationManagement/costCenter.descriptionRequired.
        /// </summary>
        public static string DescriptionRequired {
            get {
                return ResourceManager.GetString("DescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena localizada similar a allocationManagement/costCenter.letterIsRequired.
        /// </summary>
        public static string LetterIsRequired {
            get {
                return ResourceManager.GetString("LetterIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena localizada similar a allocationManagement/costCenter.letterWrong.
        /// </summary>
        public static string LetterWrong {
            get {
                return ResourceManager.GetString("LetterWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena localizada similar a allocationManagement/costCenter.save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
    }
}
