//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sofco.Resources.AdvancementAndRefund {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Advancement {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Advancement() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sofco.Resources.AdvancementAndRefund.Advancement", typeof(Advancement).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a advancementAndRefund/advancement.addSuccess.
        /// </summary>
        public static string AddSuccess {
            get {
                return ResourceManager.GetString("AddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a advancementAndRefund/advancement.advancementReturnFormNotFound.
        /// </summary>
        public static string AdvancementReturnFormNotFound {
            get {
                return ResourceManager.GetString("AdvancementReturnFormNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a advancementAndRefund/advancement.advancementReturnFormRequired.
        /// </summary>
        public static string AdvancementReturnFormRequired {
            get {
                return ResourceManager.GetString("AdvancementReturnFormRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a advancementAndRefund/advancement.ammountItemRequired.
        /// </summary>
        public static string AmmountItemRequired {
            get {
                return ResourceManager.GetString("AmmountItemRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a advancementAndRefund/advancement.analyticRequired.
        /// </summary>
        public static string AnalyticRequired {
            get {
                return ResourceManager.GetString("AnalyticRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a advancementAndRefund/advancement.cannotDelete.
        /// </summary>
        public static string CannotDelete {
            get {
                return ResourceManager.GetString("CannotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a advancementAndRefund/advancement.cannotLoad.
        /// </summary>
        public static string CannotLoad {
            get {
                return ResourceManager.GetString("CannotLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a advancementAndRefund/advancement.currencyNotFound.
        /// </summary>
        public static string CurrencyNotFound {
            get {
                return ResourceManager.GetString("CurrencyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a advancementAndRefund/advancement.currencyRequired.
        /// </summary>
        public static string CurrencyRequired {
            get {
                return ResourceManager.GetString("CurrencyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a advancementAndRefund/advancement.dateItemRequired.
        /// </summary>
        public static string DateItemRequired {
            get {
                return ResourceManager.GetString("DateItemRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a advancementAndRefund/advancement.deleteSuccess.
        /// </summary>
        public static string DeleteSuccess {
            get {
                return ResourceManager.GetString("DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a advancementAndRefund/advancement.descriptionItemRequired.
        /// </summary>
        public static string DescriptionItemRequired {
            get {
                return ResourceManager.GetString("DescriptionItemRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a advancementAndRefund/advancement.monthsReturnNotFound.
        /// </summary>
        public static string MonthsReturnNotFound {
            get {
                return ResourceManager.GetString("MonthsReturnNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a advancementAndRefund/advancement.monthsReturnRequired.
        /// </summary>
        public static string MonthsReturnRequired {
            get {
                return ResourceManager.GetString("MonthsReturnRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a advancementAndRefund/advancement.mustHaveOneDetail.
        /// </summary>
        public static string MustHaveOneDetail {
            get {
                return ResourceManager.GetString("MustHaveOneDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a advancementAndRefund/advancement.notFound.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a advancementAndRefund/advancement.nullModel.
        /// </summary>
        public static string NullModel {
            get {
                return ResourceManager.GetString("NullModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a advancementAndRefund/advancement.paymentFormRequired.
        /// </summary>
        public static string PaymentFormRequired {
            get {
                return ResourceManager.GetString("PaymentFormRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrio un error al actualizar el adelanto #{0} del solicitante {1}.
        /// </summary>
        public static string PaymentPendingError {
            get {
                return ResourceManager.GetString("PaymentPendingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a advancementAndRefund/advancement.salaryAdvancementAdded.
        /// </summary>
        public static string SalaryAdvancementAdded {
            get {
                return ResourceManager.GetString("SalaryAdvancementAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a advancementAndRefund/advancement.salaryAdvancementDeleted.
        /// </summary>
        public static string SalaryAdvancementDeleted {
            get {
                return ResourceManager.GetString("SalaryAdvancementDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a advancementAndRefund/advancement.salaryAmountGreaterThanTotalAdvancement.
        /// </summary>
        public static string SalaryAmountGreaterThanTotalAdvancement {
            get {
                return ResourceManager.GetString("SalaryAmountGreaterThanTotalAdvancement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a advancementAndRefund/advancement.salaryAmountRequired.
        /// </summary>
        public static string SalaryAmountRequired {
            get {
                return ResourceManager.GetString("SalaryAmountRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a advancementAndRefund/advancement.salaryDateRequired.
        /// </summary>
        public static string SalaryDateRequired {
            get {
                return ResourceManager.GetString("SalaryDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a advancementAndRefund/advancement.salaryDiscountNotFound.
        /// </summary>
        public static string SalaryDiscountNotFound {
            get {
                return ResourceManager.GetString("SalaryDiscountNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a advancementAndRefund/advancement.startDateReturnLessThanToday.
        /// </summary>
        public static string StartDateReturnLessThanToday {
            get {
                return ResourceManager.GetString("StartDateReturnLessThanToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a advancementAndRefund/advancement.startDateReturnRequired.
        /// </summary>
        public static string StartDateReturnRequired {
            get {
                return ResourceManager.GetString("StartDateReturnRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a advancementAndRefund/advancement.typeRequired.
        /// </summary>
        public static string TypeRequired {
            get {
                return ResourceManager.GetString("TypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a advancementAndRefund/advancement.updateSuccess.
        /// </summary>
        public static string UpdateSuccess {
            get {
                return ResourceManager.GetString("UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a advancementAndRefund/advancement.userApplicantRequired.
        /// </summary>
        public static string UserApplicantRequired {
            get {
                return ResourceManager.GetString("UserApplicantRequired", resourceCulture);
            }
        }
    }
}
