//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sofco.Resources.AdvancementAndRefund {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Refund {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Refund() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sofco.Resources.AdvancementAndRefund.Refund", typeof(Refund).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to advancementAndRefund/refund.addSuccess.
        /// </summary>
        public static string AddSuccess {
            get {
                return ResourceManager.GetString("AddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to advancementAndRefund/refund.advancementRequired.
        /// </summary>
        public static string AdvancementRequired {
            get {
                return ResourceManager.GetString("AdvancementRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to advancementAndRefund/refund.analyticRequired.
        /// </summary>
        public static string AnalyticRequired {
            get {
                return ResourceManager.GetString("AnalyticRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to advancementAndRefund/refund.detailAmmountRequired.
        /// </summary>
        public static string DetailAmmountRequired {
            get {
                return ResourceManager.GetString("DetailAmmountRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to advancementAndRefund/refund.detailDateInvalidRange.
        /// </summary>
        public static string DetailDateInvalidRange {
            get {
                return ResourceManager.GetString("DetailDateInvalidRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to advancementAndRefund/refund.detailDateRequired.
        /// </summary>
        public static string DetailDateRequired {
            get {
                return ResourceManager.GetString("DetailDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to advancementAndRefund/refund.detailDescriptionRequired.
        /// </summary>
        public static string DetailDescriptionRequired {
            get {
                return ResourceManager.GetString("DetailDescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to advancementAndRefund/refund.detailsRequired.
        /// </summary>
        public static string DetailsRequired {
            get {
                return ResourceManager.GetString("DetailsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to advancementAndRefund/refund.notFound.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to advancementAndRefund/refund.nullModel.
        /// </summary>
        public static string NullModel {
            get {
                return ResourceManager.GetString("NullModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to advancementAndRefund/refund.updateSuccess.
        /// </summary>
        public static string UpdateSuccess {
            get {
                return ResourceManager.GetString("UpdateSuccess", resourceCulture);
            }
        }
    }
}
