//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sofco.Resources.AdvancementAndRefund {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Refund {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Refund() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sofco.Resources.AdvancementAndRefund.Refund", typeof(Refund).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a advancementAndRefund/refund.addSuccess.
        /// </summary>
        public static string AddSuccess {
            get {
                return ResourceManager.GetString("AddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a advancementAndRefund/refund.advancementRequired.
        /// </summary>
        public static string AdvancementRequired {
            get {
                return ResourceManager.GetString("AdvancementRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a advancementAndRefund/refund.ammountCashReturnError.
        /// </summary>
        public static string AmmountCashReturnError {
            get {
                return ResourceManager.GetString("AmmountCashReturnError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a advancementAndRefund/refund.analyticRequired.
        /// </summary>
        public static string AnalyticRequired {
            get {
                return ResourceManager.GetString("AnalyticRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a advancementAndRefund/refund.cannotDelete.
        /// </summary>
        public static string CannotDelete {
            get {
                return ResourceManager.GetString("CannotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a advancementAndRefund/refund.creditCardNotFound.
        /// </summary>
        public static string CreditCardNotFound {
            get {
                return ResourceManager.GetString("CreditCardNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a advancementAndRefund/refund.creditCardRequired.
        /// </summary>
        public static string CreditCardRequired {
            get {
                return ResourceManager.GetString("CreditCardRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a advancementAndRefund/refund.currencyDifferentToAdvancement.
        /// </summary>
        public static string CurrencyDifferentToAdvancement {
            get {
                return ResourceManager.GetString("CurrencyDifferentToAdvancement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a advancementAndRefund/refund.currentUserEqualsDelegate.
        /// </summary>
        public static string CurrentUserEqualsDelegate {
            get {
                return ResourceManager.GetString("CurrentUserEqualsDelegate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a advancementAndRefund/refund.delegateSuccess.
        /// </summary>
        public static string DelegateSuccess {
            get {
                return ResourceManager.GetString("DelegateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a advancementAndRefund/refund.deleteSuccess.
        /// </summary>
        public static string DeleteSuccess {
            get {
                return ResourceManager.GetString("DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a advancementAndRefund/refund.detailAmmountRequired.
        /// </summary>
        public static string DetailAmmountRequired {
            get {
                return ResourceManager.GetString("DetailAmmountRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a advancementAndRefund/refund.detailDateInvalidRange.
        /// </summary>
        public static string DetailDateInvalidRange {
            get {
                return ResourceManager.GetString("DetailDateInvalidRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a advancementAndRefund/refund.detailDateRequired.
        /// </summary>
        public static string DetailDateRequired {
            get {
                return ResourceManager.GetString("DetailDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a advancementAndRefund/refund.detailDescriptionRequired.
        /// </summary>
        public static string DetailDescriptionRequired {
            get {
                return ResourceManager.GetString("DetailDescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a advancementAndRefund/refund.detailsRequired.
        /// </summary>
        public static string DetailsRequired {
            get {
                return ResourceManager.GetString("DetailsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a advancementAndRefund/refund.existLastRefund.
        /// </summary>
        public static string ExistLastRefund {
            get {
                return ResourceManager.GetString("ExistLastRefund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a advancementAndRefund/refund.hasNoAttachments.
        /// </summary>
        public static string HasNoAttachments {
            get {
                return ResourceManager.GetString("HasNoAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a advancementAndRefund/refund.notFound.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a advancementAndRefund/refund.nullModel.
        /// </summary>
        public static string NullModel {
            get {
                return ResourceManager.GetString("NullModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrio un error al actualizar el reintegro #{0} del solicitante {1}.
        /// </summary>
        public static string PaymentPendingError {
            get {
                return ResourceManager.GetString("PaymentPendingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a advancementAndRefund/refund.updateSuccess.
        /// </summary>
        public static string UpdateSuccess {
            get {
                return ResourceManager.GetString("UpdateSuccess", resourceCulture);
            }
        }
    }
}
