//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sofco.Resources.AdvancementAndRefund {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Setting {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Setting() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sofco.Resources.AdvancementAndRefund.Setting", typeof(Setting).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a advancementAndRefund/setting.amountALessThanBDolares.
        /// </summary>
        public static string AmountALessThanBDolares {
            get {
                return ResourceManager.GetString("AmountALessThanBDolares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a advancementAndRefund/setting.amountALessThanBEuros.
        /// </summary>
        public static string AmountALessThanBEuros {
            get {
                return ResourceManager.GetString("AmountALessThanBEuros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a advancementAndRefund/setting.amountALessThanBPesos.
        /// </summary>
        public static string AmountALessThanBPesos {
            get {
                return ResourceManager.GetString("AmountALessThanBPesos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a advancementAndRefund/setting.modelError.
        /// </summary>
        public static string ModelError {
            get {
                return ResourceManager.GetString("ModelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a advancementAndRefund/setting.updateSuccess.
        /// </summary>
        public static string UpdateSuccess {
            get {
                return ResourceManager.GetString("UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a advancementAndRefund/setting.valuesLessThan0.
        /// </summary>
        public static string ValuesLessThan0 {
            get {
                return ResourceManager.GetString("ValuesLessThan0", resourceCulture);
            }
        }
    }
}
