//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sofco.Resources.WorkTimeManagement {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WorkTime {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WorkTime() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sofco.Resources.WorkTimeManagement.WorkTime", typeof(WorkTime).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to workTimeManagement/workTime.addSuccess.
        /// </summary>
        public static string AddSuccess {
            get {
                return ResourceManager.GetString("AddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to workTimeManagement/workTime.analyticRequired.
        /// </summary>
        public static string AnalyticRequired {
            get {
                return ResourceManager.GetString("AnalyticRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to workTimeManagement/workTime.approvedSuccess.
        /// </summary>
        public static string ApprovedSuccess {
            get {
                return ResourceManager.GetString("ApprovedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to workTimeManagement/workTime.approvedWithSomeErrors.
        /// </summary>
        public static string ApprovedWithSomeErrors {
            get {
                return ResourceManager.GetString("ApprovedWithSomeErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to workTimeManagement/workTime.approverAdded.
        /// </summary>
        public static string ApproverAdded {
            get {
                return ResourceManager.GetString("ApproverAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to workTimeManagement/workTime.approverDeleted.
        /// </summary>
        public static string ApproverDeleted {
            get {
                return ResourceManager.GetString("ApproverDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to workTimeManagement/workTime.cannotChangeStatus.
        /// </summary>
        public static string CannotChangeStatus {
            get {
                return ResourceManager.GetString("CannotChangeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to workTimeManagement/workTime.dateOutOfRange.
        /// </summary>
        public static string DateOutOfRangeError {
            get {
                return ResourceManager.GetString("DateOutOfRangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to workTimeManagement/workTime.dateRequired.
        /// </summary>
        public static string DateRequired {
            get {
                return ResourceManager.GetString("DateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to workTimeManagement/workTime.datesRequired.
        /// </summary>
        public static string DatesRequired {
            get {
                return ResourceManager.GetString("DatesRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to workTimeManagement/workTime.deleteError.
        /// </summary>
        public static string DeleteError {
            get {
                return ResourceManager.GetString("DeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to workTimeManagement/workTime.employeeRequired.
        /// </summary>
        public static string EmployeeRequired {
            get {
                return ResourceManager.GetString("EmployeeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to workTimeManagement/workTime.hoursMaxError?{0}.
        /// </summary>
        public static string HoursMaxError {
            get {
                return ResourceManager.GetString("HoursMaxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to workTimeManagement/workTime.hoursWrong.
        /// </summary>
        public static string HoursWrong {
            get {
                return ResourceManager.GetString("HoursWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to workTimeManagement/workTime.monthError.
        /// </summary>
        public static string MonthError {
            get {
                return ResourceManager.GetString("MonthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to workTimeManagement/workTime.rejectedSuccess.
        /// </summary>
        public static string RejectedSuccess {
            get {
                return ResourceManager.GetString("RejectedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to workTimeManagement/workTime.reportWarning.
        /// </summary>
        public static string ReportWarning {
            get {
                return ResourceManager.GetString("ReportWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to workTimeManagement/workTime.searchNotFound.
        /// </summary>
        public static string SearchNotFound {
            get {
                return ResourceManager.GetString("SearchNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to workTimeManagement/workTime.sentSuccess.
        /// </summary>
        public static string SentSuccess {
            get {
                return ResourceManager.GetString("SentSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to workTimeManagement/workTime.taskRequired.
        /// </summary>
        public static string TaskRequired {
            get {
                return ResourceManager.GetString("TaskRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to workTimeManagement/workTime.userCommentMaxLengthError.
        /// </summary>
        public static string UserCommentMaxLengthError {
            get {
                return ResourceManager.GetString("UserCommentMaxLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to workTimeManagement/workTime.userRequired.
        /// </summary>
        public static string UserRequired {
            get {
                return ResourceManager.GetString("UserRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to workTimeManagement/workTime.workTimeNotFound.
        /// </summary>
        public static string WorkTimeNotFound {
            get {
                return ResourceManager.GetString("WorkTimeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to workTimeManagement/workTime.wrongApprover.
        /// </summary>
        public static string WrongApprover {
            get {
                return ResourceManager.GetString("WrongApprover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to workTimeManagement/workTime.wrongStatus.
        /// </summary>
        public static string WrongStatus {
            get {
                return ResourceManager.GetString("WrongStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to workTimeManagement/workTime.yearAndMonthRequired.
        /// </summary>
        public static string YearAndMonthRequired {
            get {
                return ResourceManager.GetString("YearAndMonthRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to workTimeManagement/workTime.yearError.
        /// </summary>
        public static string YearError {
            get {
                return ResourceManager.GetString("YearError", resourceCulture);
            }
        }
    }
}
