//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sofco.Resources.WorkTimeManagement {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WorkTime {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WorkTime() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sofco.Resources.WorkTimeManagement.WorkTime", typeof(WorkTime).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a workTimeManagement/workTime.addSuccess.
        /// </summary>
        public static string AddSuccess {
            get {
                return ResourceManager.GetString("AddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a workTimeManagement/workTime.analyticRequired.
        /// </summary>
        public static string AnalyticRequired {
            get {
                return ResourceManager.GetString("AnalyticRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aprobada.
        /// </summary>
        public static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a workTimeManagement/workTime.approvedSuccess.
        /// </summary>
        public static string ApprovedSuccess {
            get {
                return ResourceManager.GetString("ApprovedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a workTimeManagement/workTime.approvedWithSomeErrors.
        /// </summary>
        public static string ApprovedWithSomeErrors {
            get {
                return ResourceManager.GetString("ApprovedWithSomeErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a workTimeManagement/workTime.approverAdded.
        /// </summary>
        public static string ApproverAdded {
            get {
                return ResourceManager.GetString("ApproverAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a workTimeManagement/workTime.approverDeleted.
        /// </summary>
        public static string ApproverDeleted {
            get {
                return ResourceManager.GetString("ApproverDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a workTimeManagement/workTime.cannotChangeStatus.
        /// </summary>
        public static string CannotChangeStatus {
            get {
                return ResourceManager.GetString("CannotChangeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a workTimeManagement/workTime.cannotDelete.
        /// </summary>
        public static string CannotDelete {
            get {
                return ResourceManager.GetString("CannotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a workTimeManagement/workTime.dateIsHoliday.
        /// </summary>
        public static string DateIsHoliday {
            get {
                return ResourceManager.GetString("DateIsHoliday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a workTimeManagement/workTime.dateIsWeekend.
        /// </summary>
        public static string DateIsWeekend {
            get {
                return ResourceManager.GetString("DateIsWeekend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a workTimeManagement/workTime.dateOutOfRange.
        /// </summary>
        public static string DateOutOfRangeError {
            get {
                return ResourceManager.GetString("DateOutOfRangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a workTimeManagement/workTime.dateRequired.
        /// </summary>
        public static string DateRequired {
            get {
                return ResourceManager.GetString("DateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a workTimeManagement/workTime.datesRequired.
        /// </summary>
        public static string DatesRequired {
            get {
                return ResourceManager.GetString("DatesRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a workTimeManagement/workTime.deleteError.
        /// </summary>
        public static string DeleteError {
            get {
                return ResourceManager.GetString("DeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a workTimeManagement/workTime.deleteSuccess.
        /// </summary>
        public static string DeleteSuccess {
            get {
                return ResourceManager.GetString("DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Borrador.
        /// </summary>
        public static string Draft {
            get {
                return ResourceManager.GetString("Draft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a workTimeManagement/workTime.employeeRequired.
        /// </summary>
        public static string EmployeeRequired {
            get {
                return ResourceManager.GetString("EmployeeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a workTimeManagement/workTime.endDateRequired.
        /// </summary>
        public static string EndDateRequired {
            get {
                return ResourceManager.GetString("EndDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a workTimeManagement/workTime.fileEmpty.
        /// </summary>
        public static string FileEmpty {
            get {
                return ResourceManager.GetString("FileEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a workTimeManagement/workTime.hoursMaxError?{0}.
        /// </summary>
        public static string HoursMaxError {
            get {
                return ResourceManager.GetString("HoursMaxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a workTimeManagement/workTime.hoursWrong.
        /// </summary>
        public static string HoursWrong {
            get {
                return ResourceManager.GetString("HoursWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a workTimeManagement/workTime.importDateNull.
        /// </summary>
        public static string ImportDateNull {
            get {
                return ResourceManager.GetString("ImportDateNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a workTimeManagement/workTime.importDatesOutOfRange.
        /// </summary>
        public static string ImportDatesOutOfRange {
            get {
                return ResourceManager.GetString("ImportDatesOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a workTimeManagement/workTime.importDateWrong.
        /// </summary>
        public static string ImportDateWrong {
            get {
                return ResourceManager.GetString("ImportDateWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a workTimeManagement/workTime.importEmployeeIsNotInAnalytic.
        /// </summary>
        public static string ImportEmployeeIsNotInAnalytic {
            get {
                return ResourceManager.GetString("ImportEmployeeIsNotInAnalytic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a workTimeManagement/workTime.importEmployeeWithLicense.
        /// </summary>
        public static string ImportEmployeeWithLicense {
            get {
                return ResourceManager.GetString("ImportEmployeeWithLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a workTimeManagement/workTime.importHoursExceed.
        /// </summary>
        public static string ImportHoursExceed {
            get {
                return ResourceManager.GetString("ImportHoursExceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a workTimeManagement/workTime.importHoursNull.
        /// </summary>
        public static string ImportHoursNull {
            get {
                return ResourceManager.GetString("ImportHoursNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a workTimeManagement/workTime.importTaskNoExist.
        /// </summary>
        public static string ImportTaskNoExist {
            get {
                return ResourceManager.GetString("ImportTaskNoExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a workTimeManagement/workTime.importUserWithEmailNull.
        /// </summary>
        public static string ImportUserWithEmailNull {
            get {
                return ResourceManager.GetString("ImportUserWithEmailNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a workTimeManagement/workTime.invalidAllocationAssignment.
        /// </summary>
        public static string InvalidAllocationAssignment {
            get {
                return ResourceManager.GetString("InvalidAllocationAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Licencia.
        /// </summary>
        public static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a workTimeManagement/workTime.monthError.
        /// </summary>
        public static string MonthError {
            get {
                return ResourceManager.GetString("MonthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a workTimeManagement/workTime.noPendingHours.
        /// </summary>
        public static string NoPendingHours {
            get {
                return ResourceManager.GetString("NoPendingHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rechazada.
        /// </summary>
        public static string Rejected {
            get {
                return ResourceManager.GetString("Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a workTimeManagement/workTime.rejectedSuccess.
        /// </summary>
        public static string RejectedSuccess {
            get {
                return ResourceManager.GetString("RejectedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a workTimeManagement/workTime.rejectedWithSomeErrors.
        /// </summary>
        public static string RejectedWithSomeErrors {
            get {
                return ResourceManager.GetString("RejectedWithSomeErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a workTimeManagement/workTime.reportWarning.
        /// </summary>
        public static string ReportWarning {
            get {
                return ResourceManager.GetString("ReportWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a workTimeManagement/workTime.searchNotFound.
        /// </summary>
        public static string SearchNotFound {
            get {
                return ResourceManager.GetString("SearchNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pendiente de aprobación.
        /// </summary>
        public static string Sent {
            get {
                return ResourceManager.GetString("Sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a workTimeManagement/workTime.sentSuccess.
        /// </summary>
        public static string SentSuccess {
            get {
                return ResourceManager.GetString("SentSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a workTimeManagement/workTime.startDateRequired.
        /// </summary>
        public static string StartDateRequired {
            get {
                return ResourceManager.GetString("StartDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a workTimeManagement/workTime.taskRequired.
        /// </summary>
        public static string TaskRequired {
            get {
                return ResourceManager.GetString("TaskRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a workTimeManagement/workTime.userCommentMaxLengthError.
        /// </summary>
        public static string UserCommentMaxLengthError {
            get {
                return ResourceManager.GetString("UserCommentMaxLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a workTimeManagement/workTime.userRequired.
        /// </summary>
        public static string UserRequired {
            get {
                return ResourceManager.GetString("UserRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a workTimeManagement/workTime.workTimeNotFound.
        /// </summary>
        public static string WorkTimeNotFound {
            get {
                return ResourceManager.GetString("WorkTimeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a workTimeManagement/workTime.wrongApprover.
        /// </summary>
        public static string WrongApprover {
            get {
                return ResourceManager.GetString("WrongApprover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a workTimeManagement/workTime.wrongStatus.
        /// </summary>
        public static string WrongStatus {
            get {
                return ResourceManager.GetString("WrongStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a workTimeManagement/workTime.yearAndMonthRequired.
        /// </summary>
        public static string YearAndMonthRequired {
            get {
                return ResourceManager.GetString("YearAndMonthRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a workTimeManagement/workTime.yearError.
        /// </summary>
        public static string YearError {
            get {
                return ResourceManager.GetString("YearError", resourceCulture);
            }
        }
    }
}
