//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sofco.Resources.es.Billing {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    Clase de recurso fuertemente tipada para buscar cadenas localizadas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Solfac {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Solfac() {
        }
        
        /// <summary>
        ///    Devuelve la instancia de ResourceManager en caché que usa la clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sofco.Resources.es.Billing.Solfac", typeof(Solfac).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Reemplaza la propiedad CurrentUICulture del subproceso actual para todas
        ///    las búsquedas de recursos que usan esta clase de recursos fuertemente tipada.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Busca una cadena localizada similar a Solfac anulada correctamente.
        /// </summary>
        public static string CancelledSucces {
            get {
                return ResourceManager.GetString("CancelledSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena localizada similar a No se puede cambiar el estado.
        /// </summary>
        public static string CannotChangeStatus {
            get {
                return ResourceManager.GetString("CannotChangeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena localizada similar a Se debe agregar un motivo de rechazo.
        /// </summary>
        public static string CommentRequired {
            get {
                return ResourceManager.GetString("CommentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena localizada similar a Solfac eliminada correctamente.
        /// </summary>
        public static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena localizada similar a Cantidad no puede ser menor o igual a 0.
        /// </summary>
        public static string HitoQuantityRequired {
            get {
                return ResourceManager.GetString("HitoQuantityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena localizada similar a Precio Unitario no puede ser menor o igual a 0.
        /// </summary>
        public static string HitoUnitPriceRequired {
            get {
                return ResourceManager.GetString("HitoUnitPriceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena localizada similar a La Solfac ha sido facturada correctamente.
        /// </summary>
        public static string InvoicedSuccess {
            get {
                return ResourceManager.GetString("InvoicedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena localizada similar a La Solfac se ha enviado a la DAF correctamente.
        /// </summary>
        public static string InvoicePendingSuccess {
            get {
                return ResourceManager.GetString("InvoicePendingSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena localizada similar a La Solfac ha sido rechazada correctamente.
        /// </summary>
        public static string ManagementControlRejectedSuccess {
            get {
                return ResourceManager.GetString("ManagementControlRejectedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena localizada similar a Solicitud no encontrada.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena localizada similar a No se han encontrado solicitudes con esos parametros de busqueda..
        /// </summary>
        public static string NotFounds {
            get {
                return ResourceManager.GetString("NotFounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena localizada similar a La Solfac se ha enviado correctamente a Control de Gestión.
        /// </summary>
        public static string PendingByManagementControlSuccess {
            get {
                return ResourceManager.GetString("PendingByManagementControlSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena localizada similar a Los porcetanjes no pueden ser menor a 0.
        /// </summary>
        public static string PercentageLessThan0 {
            get {
                return ResourceManager.GetString("PercentageLessThan0", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena localizada similar a La provincia es requerida si se incluye un porcentaje .
        /// </summary>
        public static string ProvinceRequired {
            get {
                return ResourceManager.GetString("ProvinceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena localizada similar a Solicitud de facturación creada correctamente.
        /// </summary>
        public static string SolfacCreated {
            get {
                return ResourceManager.GetString("SolfacCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena localizada similar a El plazo no puede ser menor a 0.
        /// </summary>
        public static string TimeLimitLessThan0 {
            get {
                return ResourceManager.GetString("TimeLimitLessThan0", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Busca una cadena localizada similar a La suma de porcentajes no puede ser distinta a 100%.
        /// </summary>
        public static string TotalPercentageError {
            get {
                return ResourceManager.GetString("TotalPercentageError", resourceCulture);
            }
        }
    }
}
